### ISSUE TITLE
readme.md:56: Add explanation for enrolling, searching...

### ISSUE THREAD

**Issue by 0pdd** [nikialeksey/fpscanner#1]
The puzzle `none-e3b7ba57` from #none has to be resolved:

https://github.com/nikialeksey/fpscanner/blob/dd76a9ef18116d039419ac78c83a76fb8c89fec7/readme.md#L56-L56

The puzzle was created by Alexey Nikitin on 26-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by gulsezim11** [comment]
Hello. Currently, I am doing a project which is connected with fingerprint authentication, and upon the start of library trial, I have encountered to one problem:

This error message is emerging from code that is on official page of fpscanner website:

 
![500389A545CA489E8C6234AD9F6BC007](https://user-images.githubusercontent.com/38872591/72278554-753d5180-365e-11ea-9893-d3de1d36360e.png)


 with SerialPort(Serial(port='COM3', baudrate=9600 * 6, timeout=2)) as port:

              rq = RqCommand(port)

              rs = RsSimple(port)

              print 'Waiting for finger...'          

              while not Scan(rq, rs).is_scanned():

                             pass

              print 'Finger has been scanned! Downloading the finger image...'

              image = UpImage(rq, rs).image()

              image.show()

 I would like to know how this error can be resolved?

**Comment by 0pdd** [comment]
The puzzle `none-e3b7ba57` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#5](https://github.com/nikialeksey/fpscanner/issues/5) is still not solved.
