### ISSUE TITLE
What's the difference with pyfingerprint ?

### ISSUE THREAD

**Issue by doudz** [nikialeksey/fpscanner#2]
What's the difference with pyfingerprint ?
advantage ?

pyfingerprint is a single file module, while your lib looks a bit more complex but why ?

**Comment by nikialeksey** [comment]
I've tried to create library with Object Oriented style. `pyfingerprint` really consists of one file. But when I tried to interact with it I was confused: more then thousand LoC, many constants, functions in one file. It's hard for understanding, is not?

It's analogue of `pyfingerprint`, nothing else

**Comment by doudz** [comment]
Thanks for clarification.
