### ISSUE TITLE
error while using fpscanner library

### ISSUE THREAD

**Issue by gulsezim11** [nikialeksey/fpscanner#3]
Hello. Currently, I am doing a project which is connected with fingerprint authentication, and upon the start of library trial, I have encountered to one problem:

This error message is emerging from code that is on official page of fpscanner website:

![500389A545CA489E8C6234AD9F6BC007](https://user-images.githubusercontent.com/38872591/72278843-0f04fe80-365f-11ea-972e-aed3c824df5d.png)

with SerialPort(Serial(port='COM3', baudrate=9600 * 6, timeout=2)) as port:

          rq = RqCommand(port)

          rs = RsSimple(port)

          print 'Waiting for finger...'          

          while not Scan(rq, rs).is_scanned():

                         pass

          print 'Finger has been scanned! Downloading the finger image...'

          image = UpImage(rq, rs).image()

          image.show()
I would like to know how this error can be resolved? All requirements are installed

**Comment by nikialeksey** [comment]
Hello!

I have tested my library only with one device - FPM 10A (https://aliexpress.ru/item/32834946780.html), and there is all good. Could you please provide me information about your finger print scanner device?

**Comment by nikialeksey** [comment]
In the private email messages we dicsuss and decide, that connection was incorrect. So, close the issue
